name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build -- --configuration=production
      - name: Verify build
        run: |
          ls -la dist/stud-portal/
          du -sh dist/stud-portal/
      - name: Load .env file
        run: |
          echo "Debug: Checking for .env file"
          if [ -f .env ]; then
            echo "Debug: .env file found"
            cat .env
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$(grep AZURE_STATIC_WEB_APPS_API_TOKEN .env | cut -d'=' -f2)" >> $GITHUB_ENV
            echo "Debug: Token loaded from .env: ${AZURE_STATIC_WEB_APPS_API_TOKEN}"
          else
            echo "Debug: .env file not found"
            exit 1
          fi
      - name: Deploy
        run: |
          echo "Debug: Starting deployment"
          echo "Debug: Using token: ${AZURE_STATIC_WEB_APPS_API_TOKEN}"
          azure_static_web_apps_api_token="${AZURE_STATIC_WEB_APPS_API_TOKEN}" \
          repo_token="${{ secrets.GITHUB_TOKEN }}" \
          action="upload" \
          app_location="/" \
          output_location="dist/stud-portal" \
          /usr/bin/docker run --rm \
            -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN \
            -e INPUT_REPO_TOKEN \
            -e INPUT_ACTION \
            -e INPUT_APP_LOCATION \
            -e INPUT_OUTPUT_LOCATION \
            -v "$(pwd)":/github/workspace \
            azure/static-web-apps-deploy:v1
        env:
          DEBUG: "true"