name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Debug: Current working directory: $(pwd)"
          echo "Debug: Installing dependencies"
          npm install --legacy-peer-deps
          echo "Debug: Dependencies installed, checking node_modules"
          ls -la node_modules/
          echo "Debug: Node version"
          node --version
          echo "Debug: NPM version"
          npm --version

      - name: Verify Angular CLI
        run: |
          echo "Debug: Verifying Angular CLI installation"
          npm install -g @angular/cli
          ng version

      - name: Build
        run: |
          echo "Debug: Starting build"
          npm run build -- --configuration=production
          echo "Debug: Build completed, verifying output"
          if [ -d "dist/stud-portal/browser" ]; then
            echo "Debug: Contents of dist/stud-portal/browser"
            ls -la dist/stud-portal/browser/
            echo "Debug: Size of dist/stud-portal/browser"
            du -sh dist/stud-portal/browser/
            echo "Debug: Checking for index.html"
            if [ -f "dist/stud-portal/browser/index.html" ]; then
              echo "Debug: index.html found"
              cat dist/stud-portal/browser/index.html
            else
              echo "Error: index.html not found in dist/stud-portal/browser"
              exit 1
            fi
          else
            echo "Error: dist/stud-portal/browser directory not found"
            exit 1
          fi

      - name: Debug Environment
        run: |
          echo "Debug: Current working directory: $(pwd)"
          echo "Debug: GitHub workspace: $GITHUB_WORKSPACE"
          echo "Debug: Repository secret name: AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E"
          echo "Debug: Token status: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E != '' && 'Set' || 'Not Set' }}"
          echo "Debug: Action runner OS: $RUNNER_OS"
          echo "Debug: Git status"
          git status
          echo "Debug: Git branch"
          git branch --show-current
          echo "Debug: Environment variables"
          env | sort
          echo "Debug: Checking Azure Static Web Apps configuration"
          echo "Debug: App location: /"
          echo "Debug: Output location: dist/stud-portal/browser"

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/stud-portal/browser"
          skip_app_build: true
        env:
          DEBUG: "true"

      - name: Debug Deployment Failure
        if: failure()
        run: |
          echo "Debug: Deployment failed, checking for additional details"
          echo "Debug: Deployment ID: ${{ steps.deploy.outputs.deployment_id }}"
          echo "Debug: Checking Azure Static Web Apps CLI for diagnostics"
          npm install -g @azure/static-web-apps-cli
          swa --version
          echo "Debug: Attempting to validate token (non-intrusive check)"
          echo "Debug: Token length: ${#AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E}"
          echo "Debug: Listing files in output location for verification"
          ls -la dist/stud-portal/browser/

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E }}
          action: "close"