name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Debug: Installing dependencies"
          npm install --legacy-peer-deps
          echo "Debug: Dependencies installed, checking node_modules"
          ls -la node_modules/

      - name: Build
        run: |
          echo "Debug: Starting build"
          npm run build -- --configuration=production
          echo "Debug: Build completed, verifying output"
          if [ -d "dist/stud-portal" ]; then
            ls -la dist/stud-portal/
            du -sh dist/stud-portal/
          else
            echo "Debug: dist/stud-portal directory not found"
            exit 1
          fi

      - name: Debug Environment
        run: |
          echo "Debug: Current working directory: $(pwd)"
          echo "Debug: GitHub workspace: $GITHUB_WORKSPACE"
          echo "Debug: Repository secret name: AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E"
          echo "Debug: Token status: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E != '' && 'Set' || 'Not Set' }}"
          echo "Debug: Action runner OS: $RUNNER_OS"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_090A7891E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/stud-portal"
        env:
          DEBUG: "true"