name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build -- --configuration=production
      - name: Verify build
        run: |
          ls -la dist/stud-portal/
          du -sh dist/stud-portal/
      - name: Load .env file
        run: |
          echo "Debug: Checking for .env file"
          if [ -f .env ]; then
            echo "Debug: .env file found"
            cat .env
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=$(grep AZURE_STATIC_WEB_APPS_API_TOKEN .env | cut -d'=' -f2)" >> $GITHUB_ENV
            echo "Debug: Token loaded from .env: ${AZURE_STATIC_WEB_APPS_API_TOKEN}"
          else
            echo "Debug: .env file not found"
            exit 1
          fi
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/stud-portal"
        env:
          DEBUG: "true"