name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Debug: Installing dependencies"
          npm install --legacy-peer-deps

      - name: Verify Angular CLI
        run: |
          echo "Debug: Verifying Angular CLI"
          npm install -g @angular/cli
          ng version

      - name: Build
        run: |
          echo "Debug: Starting build"
          npm run build -- --configuration=production
          echo "Debug: Build completed, verifying output"
          if [ -d "dist/rotsvas-portal" ]; then
            echo "Debug: Contents of dist/rotsvas-portal"
            ls -la dist/rotsvas-portal/
            if [ -f "dist/rotsvas-portal/index.html" ]; then
              echo "Debug: index.html found"
            else
              echo "Error: index.html not found in dist/rotsvas-portal"
              exit 1
            fi
          else
            echo "Error: dist/rotsvas-portal directory not found"
            exit 1
          fi

      - name: Deploy
        env:
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          echo "Debug: Deploying with SWA CLI"
          npm install -g @azure/static-web-apps-cli@latest
          swa deploy --app-location "/" --output-location "dist/rotsvas-portal" --data-api-location "" --app-name "asksphere-frontend" --deployment-token "$DEPLOYMENT_TOKEN" --verbose

      - name: Debug Deployment Failure
        if: failure()
        run: |
          echo "Debug: Deployment failed, checking output"
          ls -la dist/rotsvas-portal/
          echo "Debug: Verifying token"
          echo "Token set: ${{ secrets.DEPLOYMENT_TOKEN != '' && 'Yes' || 'No' }}"

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          action: "close"
